#!/bin/bash

bspc rule -r "*"

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

feh --bg-scale ~/Pictures/Wallpapers/japan_artwork.jpg &
compton &

# polybar
~/.config/polybar/launch.sh &


# window switcher
# ~/Documents/scripts/wswr.sh -r &

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.58
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a "Microsoft Teams - Preview" desktop='^8'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
bspc rule -a Glade-previewer state=floating

# color
bspc config normal_border_color  "#74737c"
bspc config focused_border_color "#093748"
bspc config urgent_border_color  "#c33027"

# fix cursor display x when not hover on window
xsetroot -cursor_name left_ptr &

# startup applications (executed once)
~/Documents/scripts/startup.sh &

